basePath: /api/v1
definitions:
  main.createBoxOkResponse:
    properties:
      cell_id:
        type: integer
      id:
        type: integer
      name:
        type: string
    type: object
  main.createCellOkResponse:
    properties:
      id:
        type: integer
      name:
        type: string
      storage_id:
        type: integer
    type: object
  main.createStorageOkResponse:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  main.getCellsOkResponse:
    properties:
      cells:
        items:
          properties:
            id:
              type: integer
            name:
              type: string
            storage_id:
              type: integer
          type: object
        type: array
    type: object
  main.getStoragesOkResponse:
    properties:
      storages:
        items:
          properties:
            id:
              type: integer
            name:
              type: string
            user_id:
              type: integer
          type: object
        type: array
    type: object
info:
  contact: {}
  description: API for storage-api-gateway
  title: Storage-Master API
  version: "1.0"
paths:
  /boxes:
    post:
      consumes:
      - application/json
      description: Create new named box connected to cell
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.createBoxOkResponse'
        "400":
          description: Bad request
          schema:
            type: string
        "405":
          description: Method is not supported
          schema:
            type: string
        "500":
          description: Storage service failed
          schema:
            type: string
      summary: Create new box
      tags:
      - boxes
  /cells:
    get:
      consumes:
      - application/json
      description: Get all cells by given storage_id with permission checking
      parameters:
      - description: Storage ID
        in: query
        name: storage_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.getCellsOkResponse'
        "400":
          description: Bad request
          schema:
            type: string
        "403":
          description: You don't have enough permissions
          schema:
            type: string
        "405":
          description: Method is not supported
          schema:
            type: string
        "500":
          description: Storage service failed
          schema:
            type: string
      summary: Get cells by storage_id
      tags:
      - cells
    post:
      consumes:
      - application/json
      description: Create new named cell connected to storage to store boxes
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.createCellOkResponse'
        "400":
          description: Bad request
          schema:
            type: string
        "405":
          description: Method is not supported
          schema:
            type: string
        "500":
          description: Storage service failed
          schema:
            type: string
      summary: Create new cell
      tags:
      - cells
  /storages:
    get:
      consumes:
      - application/json
      description: Get all storage instances related to the given user_id
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.getStoragesOkResponse'
        "400":
          description: Bad request
          schema:
            type: string
        "403":
          description: You dont't have enough permissions
          schema:
            type: string
        "405":
          description: Method is not supported
          schema:
            type: string
        "500":
          description: Storage service failed
          schema:
            type: string
      summary: Get storages by user_id
      tags:
      - storages
    post:
      consumes:
      - application/json
      description: Create new named storage to store cells
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.createStorageOkResponse'
        "400":
          description: Bad request
          schema:
            type: string
        "405":
          description: Method is not supported
          schema:
            type: string
        "500":
          description: Storage service failed
          schema:
            type: string
      summary: Create new storage
      tags:
      - storages
swagger: "2.0"
